services:
  dailymart-backend:
    container_name: dailymart-backend
    build:
      context: .
      target: production
    # volumes:
    # - ./:/app
    # - /app/node_modules
    # - ./node_modules:/app/node_modules # Ensures node_modules is accessible
    environment:
      NODE_ENV: production
    depends_on:
      - redis
      - dailymart-db
      - dailymart-mongo

  dailymart-mongo:
    image: mongo:latest
    container_name: dailymart-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - '5544:27017' # Only expose if needed externally

  dailymart-db:
    image: postgres:latest
    container_name: dailymart-db
    environment:
      POSTGRES_USER: dailymart
      POSTGRES_PASSWORD: dailymart@123
      POSTGRES_DB: dailymart
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5555:5432' # Only expose if needed externally

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379' # Only expose if needed externally
      - '8001:8001'

volumes:
  postgres_data:
  redis_data:
  mongo_data:
